apiVersion: apps/v1
kind: Deployment  
metadata:
  name: backend-app
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  strategy: 
    type: RollingUpdate 
  template: 
    metadata: 
      labels:
        app: backend-app 
    spec:
      containers:
      - name: backend-app 
        image: sameerpatlekar/backend
        ports:
        - name: java
          containerPort: 8080
          protocol: TCP 

---

apiVersion: v1 
kind: Service 
metadata: 
  name: backend-service
spec: 
  selector: 
    app: backend-app 
  ports: 
  - name: http 
    targetPort: 3306 
    port: 3306
  type: ClusterIP
