apiVersion: apps/v1
kind: Deployment  
metadata:
  name: frontend-app
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  strategy: 
    type: RollingUpdate 
  template: 
    metadata: 
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: sameerpatlekar/studentapp
        ports:
        - name: tomcat
          containerPort: 8080
          protocol: TCP 

---

apiVersion: v1 
kind: Service 
metadata: 
  name: frontend-service
spec: 
  selector: 
    app: frontend-app 
  ports: 
  - name: http 
    targetPort: 8080 
    port: 80
  type: LoadBalancer 