apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend
data:
  context.xml: |
    <Context>
        <Resource name="jdbc/mydb" auth="Container" type="javax.sql.DataSource"
                  maxTotal="100" maxIdle="30" maxWaitMillis="10000"
                  username="${DATABASE_USERNAME}" password="${DATABASE_PASSWORD}"
                  driverClassName="com.mysql.cj.jdbc.Driver"
                  url="${DATABASE_URL}"/>
    </Context>
