apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-connector-pv
  namespace: backend
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/sameer/files"
