apiVersion: v1
kind: PersistentVolume
metadata:
  name: webapps-pv
  namespace: backend
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/webapps"
