apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace : backend
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: pvc-mysql
        - name: initdb
          configMap:
            name: my-config
            items:
              - key: init.sql
                path: init.sql
      containers:
        - name: mysql
          image: mariadb
          command: ['sh', '-c', 'until mysql -u"$DATABASE_USERNAME" -p"$DATABASE_PASSWORD" -e "SELECT 1" > /dev/null 2>&1; do echo "Waiting for MySQL..."; sleep 1; done; cat /docker-entrypoint-initdb.d/init.sql | mysql -u"$DATABASE_USERNAME" -p"$DATABASE_PASSWORD"']
          env:
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: database.username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: database.password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: backend
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
