apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: pvc-mysql
        - name: initdb
          configMap:
            name: mysql-initdb-config
      initContainers:
        - name: init-mysql-db
          image: mysql:5.7
          command: ['sh', '-c', 'cat /docker-entrypoint-initdb.d/init.sql | mysql -uroot -p"$MYSQL_ROOT_PASSWORD"']
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "yourpassword"  # Ensure this matches with the main container
          volumeMounts:
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "yourpassword"
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
