apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
  namespace: backend
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
