---
- name: Create Database Schema in AWS RDS
  hosts: localhost
  vars:
    db_instance_endpoint: localhost
    db_instance_port: 10000
    db_name: "studentapp"
    db_user: "admin"
    db_password: "admin123"
  tasks:
    - name: Create database schema
      community.mysql.mysql_db:
        login_host: "{{ db_instance_endpoint }}"
        login_port: "{{ db_instance_port }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        name: "{{ db_name }}"
        state: present
    
    - name: Create table in the database schema
      mysql_query:
        login_db: "{{ db_name }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ db_instance_endpoint }}"
        query: >
          CREATE TABLE if not exists students(
            student_id INT NOT NULL AUTO_INCREMENT,student_name VARCHAR(100) NOT NULL,
            student_addr VARCHAR(100) NOT NULL,student_age VARCHAR(3) NOT NULL,student_qual VARCHAR(20) NOT NULL,student_percent VARCHAR(10) NOT NULL,student_year_passed VARCHAR(10) NOT NULL,PRIMARY KEY (student_id)
          );



