---
- name: Create Database Schema in AWS RDS
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
    db_host: localhost
    mysql_port: 10002
    db_name: "studentapp"
    mysql_user: "admin"
    mysql_password: "admin123"
  tasks:
    - name: Update apt package list
      apt:
        update_cache: yes
    - name: Create database schema
      community.mysql.mysql_db:
        login_host: "{{ db_host }}"
        login_port: "{{ mysql_port }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        name: "{{ db_name }}"
        state: present
        login_unix_socket: null
    
    - name: Create table in the database schema
      mysql_query:
        login_db: "{{ db_name }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_host: "{{ db_host }}"
        query: >
          CREATE TABLE if not exists students(
            student_id INT NOT NULL AUTO_INCREMENT,student_name VARCHAR(100) NOT NULL,
            student_addr VARCHAR(100) NOT NULL,student_age VARCHAR(3) NOT NULL,student_qual VARCHAR(20) NOT NULL,student_percent VARCHAR(10) NOT NULL,student_year_passed VARCHAR(10) NOT NULL,PRIMARY KEY (student_id)
          );
        login_unix_socket: null
    - name: Connect to MySQL and run a simple query
      shell: mysql -h {{ db_host }} -P {{ mysql_port }} -u {{ mysql_user }} -p{{ mysql_password }} --protocol=TCP -e "SHOW DATABASES;"
      register: mysql_result
    - debug:
        var: mysql_result.stdout

