apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  namespace: backend
data:
  database.url: jdbc:mysql://localhost:3306/studentapp
  database.username: root
  context.xml: |
    <Context>
        <Resource name="jdbc/mydb" auth="Container" type="javax.sql.DataSource"
                  maxTotal="100" maxIdle="30" maxWaitMillis="10000"
                  username="${DATABASE_USERNAME}" password="${DATABASE_PASSWORD}"
                  driverClassName="com.mysql.cj.jdbc.Driver"
                  url="${DATABASE_URL}"/>
    </Context>
    
  init.sql:
    
    CREATE DATABASE IF NOT EXISTS studentapp;
    USE studentapp;

    CREATE TABLE IF NOT EXISTS students (
	      student_id INT NOT NULL AUTO_INCREMENT,
	      student_name VARCHAR(100) NOT NULL,
	      student_addr VARCHAR(100) NOT NULL,
	      student_age VARCHAR(3) NOT NULL,
	      student_qual VARCHAR(20) NOT NULL,
	      student_percent VARCHAR(10) NOT NULL,
	      student_year_passed VARCHAR(10) NOT NULL,
	      PRIMARY KEY (student_id)
	    ); 
