apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: sameerpatlekar/tomcat-java
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: database.url
        - name: DATABASE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: database.username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: database.password
        volumeMounts:
        - name: config-volume
          mountPath: /usr/local/tomcat/conf/context.xml
          subPath: context.xml
      volumes:
      - name: config-volume
        configMap:
          name: backend-config
          items:
          - key: context.xml
            path: context.xml
   
---

apiVersion: v1 
kind: Service 
metadata: 
  name: frontend-service
spec: 
  selector: 
    app: tomcat
  ports: 
  - name: http 
    targetPort: 8080 
    port: 80
  type: NodePort