apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: sameerpatlekar/frontend
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: database.url
        - name: DATABASE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: database.username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: database.password
        
---

apiVersion: v1 
kind: Service 
metadata: 
  name: my-service
  namespace: backend
spec: 
  selector: 
    app: tomcat
  ports: 
  - name: http 
    targetPort: 8080 
    port: 80
  type: NodePort