apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-connector-pvc
  namespace: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
